<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>walt</string>
	</array>
	<key>name</key>
	<string>Walter</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>_comment</key>
			<string>_blockComment</string>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>source.walt</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(.|\*)*</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[]bool</string>
			<key>match</key>
			<string>\[\]bool</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[]float</string>
			<key>match</key>
			<string>\[\]float</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[]int32</string>
			<key>match</key>
			<string>\[\]int32</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[]int64</string>
			<key>match</key>
			<string>\[\]int64</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>if</string>
			<key>match</key>
			<string>(\b)if(\b)</string>
			<key>name</key>
			<string>keyword.control.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[]double</string>
			<key>match</key>
			<string>\[\]double</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[]string</string>
			<key>match</key>
			<string>\[\]string</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[]uint32</string>
			<key>match</key>
			<string>\[\]uint32</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[]uint64</string>
			<key>match</key>
			<string>\[\]uint64</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>else</string>
			<key>match</key>
			<string>(\b)else(\b)</string>
			<key>name</key>
			<string>keyword.control.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>root</string>
			<key>match</key>
			<string>(\b)root(\b)</string>
			<key>name</key>
			<string>keyword.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>then</string>
			<key>match</key>
			<string>(\b)then(\b)</string>
			<key>name</key>
			<string>keyword.control.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>true</string>
			<key>match</key>
			<string>(\b)true(\b)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>[][]byte</string>
			<key>match</key>
			<string>\[\]\[\]byte</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>false</string>
			<key>match</key>
			<string>(\b)false(\b)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>space</string>
			<key>match</key>
			<string>((\/\/.*$)|(\/\*(.|\*)*\*\/))|([ ]|\t|$|\r)</string>
			<key>name</key>
			<string>comment.block.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>id</string>
			<key>match</key>
			<string>((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>uint32_lit</string>
			<key>match</key>
			<string>(uint32)\((((([1-9])(([0-9]))*)|(0(([0-7]))*)|(0(x|X)([0-9]|[A-F]|[a-f])(([0-9]|[A-F]|[a-f]))*)))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>uint64_lit</string>
			<key>match</key>
			<string>(uint64)\((((([1-9])(([0-9]))*)|(0(([0-7]))*)|(0(x|X)([0-9]|[A-F]|[a-f])(([0-9]|[A-F]|[a-f]))*)))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>int32_lit</string>
			<key>match</key>
			<string>(int32)\(((-?((([1-9])(([0-9]))*)|(0(([0-7]))*)|(0(x|X)([0-9]|[A-F]|[a-f])(([0-9]|[A-F]|[a-f]))*))))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>int64_lit</string>
			<key>match</key>
			<string>(int64)\(((-?((([1-9])(([0-9]))*)|(0(([0-7]))*)|(0(x|X)([0-9]|[A-F]|[a-f])(([0-9]|[A-F]|[a-f]))*))))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>float_var</string>
			<key>match</key>
			<string>\$(float)\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>int32_var</string>
			<key>match</key>
			<string>\$(int32)\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>int64_var</string>
			<key>match</key>
			<string>\$(int64)\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>double_var</string>
			<key>match</key>
			<string>\$(double)\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>uint32_var</string>
			<key>match</key>
			<string>\$(uint32)\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>uint64_var</string>
			<key>match</key>
			<string>\$(uint64)\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>bytes_var</string>
			<key>match</key>
			<string>\$(\[\]byte)\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>bool_var</string>
			<key>match</key>
			<string>\$((\b)bool(\b))\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>string_var</string>
			<key>match</key>
			<string>\$((\b)string(\b))\(((((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*)(\.((([A-Z])|([a-z])|_)((([A-Z])|([a-z])|_|([0-9])))*))*))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>string_lit</string>
			<key>match</key>
			<string>(\`.*\`)|("((.|(\\u([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))|(\\U([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))|(\\(a|b|f|n|r|t|v|\\|'|")))|((\\([0-7])([0-7])([0-7]))|(\\x([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))))*")</string>
			<key>name</key>
			<string>string.interpolated.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>float_lit</string>
			<key>match</key>
			<string>(float)\((-?((((([0-9])(([0-9]))*)\.(([0-9])(([0-9]))*)((e|E)(\+|-)?(([0-9])(([0-9]))*)))|((([0-9])(([0-9]))*)\.((([0-9])(([0-9]))*)|((e|E)(\+|-)?(([0-9])(([0-9]))*))))|((([0-9])(([0-9]))*)((e|E)(\+|-)?(([0-9])(([0-9]))*)))|(\.(([0-9])(([0-9]))*)(((e|E)(\+|-)?(([0-9])(([0-9]))*)))?))|((([1-9])(([0-9]))*)|(0(([0-7]))*)|(0(x|X)([0-9]|[A-F]|[a-f])(([0-9]|[A-F]|[a-f]))*))))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>double_lit</string>
			<key>match</key>
			<string>(double)\((-?((((([0-9])(([0-9]))*)\.(([0-9])(([0-9]))*)((e|E)(\+|-)?(([0-9])(([0-9]))*)))|((([0-9])(([0-9]))*)\.((([0-9])(([0-9]))*)|((e|E)(\+|-)?(([0-9])(([0-9]))*))))|((([0-9])(([0-9]))*)((e|E)(\+|-)?(([0-9])(([0-9]))*)))|(\.(([0-9])(([0-9]))*)(((e|E)(\+|-)?(([0-9])(([0-9]))*)))?))|((([1-9])(([0-9]))*)|(0(([0-7]))*)|(0(x|X)([0-9]|[A-F]|[a-f])(([0-9]|[A-F]|[a-f]))*))))\)</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
		<dict>
			<key>_comment</key>
			<string>bytes_lit</string>
			<key>match</key>
			<string>(\[\]byte)\{((([ ]|\t|$|\r))*((((([1-9])(([0-9]))*)|(0(([0-7]))*)|(0(x|X)([0-9]|[A-F]|[a-f])(([0-9]|[A-F]|[a-f]))*))|('((.|(\\u([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))|(\\U([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))|(\\(a|b|f|n|r|t|v|\\|'|")))|((\\([0-7])([0-7])([0-7]))|(\\x([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))))'))((([ ]|\t|$|\r))*,(([ ]|\t|$|\r))*(((([1-9])(([0-9]))*)|(0(([0-7]))*)|(0(x|X)([0-9]|[A-F]|[a-f])(([0-9]|[A-F]|[a-f]))*))|('((.|(\\u([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))|(\\U([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))|(\\(a|b|f|n|r|t|v|\\|'|")))|((\\([0-7])([0-7])([0-7]))|(\\x([0-9]|[A-F]|[a-f])([0-9]|[A-F]|[a-f]))))')))*)?(([ ]|\t|$|\r))*)\}</string>
			<key>name</key>
			<string>source.walt</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.walt</string>
	<key>uuid</key>
	<string>94f96cd0-fc89-4d48-7e58-def59eb550e8</string>
</dict>
</plist>
